"""create initial tables

Revision ID: c34a01950fe8
Revises: 
Create Date: 2025-12-18 14:54:38.914507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34a01950fe8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('applied_filters_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_reports_created_at', 'saved_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_reports_id'), 'saved_reports', ['id'], unique=False)
    op.create_index(op.f('ix_saved_reports_report_name'), 'saved_reports', ['report_name'], unique=False)
    op.create_table('transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='maintransactiontype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('main_type', 'name', name='uix_main_type_name')
    )
    op.create_index(op.f('ix_transaction_types_main_type'), 'transaction_types', ['main_type'], unique=False)
    op.create_index(op.f('ix_transaction_types_name'), 'transaction_types', ['name'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('RON', 'EUR', 'USD', name='currency'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence', sa.Enum('NONE', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurrence'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['transaction_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    op.create_index(op.f('ix_transaction_is_recurring'), 'transaction', ['is_recurring'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_type_id'), 'transaction', ['transaction_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_type_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_is_recurring'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_transaction_types_name'), table_name='transaction_types')
    op.drop_index(op.f('ix_transaction_types_main_type'), table_name='transaction_types')
    op.drop_table('transaction_types')
    op.drop_index(op.f('ix_saved_reports_report_name'), table_name='saved_reports')
    op.drop_index(op.f('ix_saved_reports_id'), table_name='saved_reports')
    op.drop_index('ix_saved_reports_created_at', table_name='saved_reports')
    op.drop_table('saved_reports')
    # ### end Alembic commands ###
